export const COUNTRIES = [
  { code: "US", name: "United States",   flag: "🇺🇸", dial: "+1",   currency: "USD" },
  { code: "GB", name: "United Kingdom",  flag: "🇬🇧", dial: "+44",  currency: "GBP" },
  { code: "CA", name: "Canada",          flag: "🇨🇦", dial: "+1",   currency: "CAD" },
  { code: "AU", name: "Australia",       flag: "🇦🇺", dial: "+61",  currency: "AUD" },
  { code: "IN", name: "India",           flag: "🇮🇳", dial: "+91",  currency: "INR" },
  { code: "PK", name: "Pakistan",        flag: "🇵🇰", dial: "+92",  currency: "PKR" },
  { code: "BD", name: "Bangladesh",      flag: "🇧🇩", dial: "+880", currency: "BDT" },
  { code: "PH", name: "Philippines",     flag: "🇵🇭", dial: "+63",  currency: "PHP" },
  { code: "NG", name: "Nigeria",         flag: "🇳🇬", dial: "+234", currency: "NGN" },
  { code: "GH", name: "Ghana",           flag: "🇬🇭", dial: "+233", currency: "GHS" },
  { code: "ZA", name: "South Africa",    flag: "🇿🇦", dial: "+27",  currency: "ZAR" },
  { code: "KE", name: "Kenya",           flag: "🇰🇪", dial: "+254", currency: "KES" },
  { code: "DE", name: "Germany",         flag: "🇩🇪", dial: "+49",  currency: "EUR" },
  { code: "FR", name: "France",          flag: "🇫🇷", dial: "+33",  currency: "EUR" },
  { code: "IT", name: "Italy",           flag: "🇮🇹", dial: "+39",  currency: "EUR" },
  { code: "ES", name: "Spain",           flag: "🇪🇸", dial: "+34",  currency: "EUR" },
  { code: "NL", name: "Netherlands",     flag: "🇳🇱", dial: "+31",  currency: "EUR" },
  { code: "SE", name: "Sweden",          flag: "🇸🇪", dial: "+46",  currency: "SEK" },
  { code: "NO", name: "Norway",          flag: "🇳🇴", dial: "+47",  currency: "NOK" },
  { code: "PL", name: "Poland",          flag: "🇵🇱", dial: "+48",  currency: "PLN" },
  { code: "UA", name: "Ukraine",         flag: "🇺🇦", dial: "+380", currency: "UAH" },
  { code: "RO", name: "Romania",         flag: "🇷🇴", dial: "+40",  currency: "RON" },
  { code: "TR", name: "Turkey",          flag: "🇹🇷", dial: "+90",  currency: "TRY" },
  { code: "AE", name: "UAE",             flag: "🇦🇪", dial: "+971", currency: "AED" },
  { code: "SA", name: "Saudi Arabia",    flag: "🇸🇦", dial: "+966", currency: "SAR" },
  { code: "EG", name: "Egypt",           flag: "🇪🇬", dial: "+20",  currency: "EGP" },
  { code: "IL", name: "Israel",          flag: "🇮🇱", dial: "+972", currency: "ILS" },
  { code: "MA", name: "Morocco",         flag: "🇲🇦", dial: "+212", currency: "MAD" },
  { code: "BR", name: "Brazil",          flag: "🇧🇷", dial: "+55",  currency: "BRL" },
  { code: "MX", name: "Mexico",          flag: "🇲🇽", dial: "+52",  currency: "MXN" },
  { code: "AR", name: "Argentina",       flag: "🇦🇷", dial: "+54",  currency: "ARS" },
  { code: "CO", name: "Colombia",        flag: "🇨🇴", dial: "+57",  currency: "COP" },
  { code: "SG", name: "Singapore",       flag: "🇸🇬", dial: "+65",  currency: "SGD" },
  { code: "MY", name: "Malaysia",        flag: "🇲🇾", dial: "+60",  currency: "MYR" },
  { code: "ID", name: "Indonesia",       flag: "🇮🇩", dial: "+62",  currency: "IDR" },
  { code: "TH", name: "Thailand",        flag: "🇹🇭", dial: "+66",  currency: "THB" },
  { code: "VN", name: "Vietnam",         flag: "🇻🇳", dial: "+84",  currency: "VND" },
  { code: "JP", name: "Japan",           flag: "🇯🇵", dial: "+81",  currency: "JPY" },
  { code: "KR", name: "South Korea",     flag: "🇰🇷", dial: "+82",  currency: "KRW" },
  { code: "NZ", name: "New Zealand",     flag: "🇳🇿", dial: "+64",  currency: "NZD" },
];

export const CURRENCIES = [
  { code: "USD", label: "USD — US Dollar" },
  { code: "GBP", label: "GBP — British Pound" },
  { code: "EUR", label: "EUR — Euro" },
  { code: "CAD", label: "CAD — Canadian Dollar" },
  { code: "AUD", label: "AUD — Australian Dollar" },
  { code: "INR", label: "INR — Indian Rupee" },
  { code: "PKR", label: "PKR — Pakistani Rupee" },
  { code: "BDT", label: "BDT — Bangladeshi Taka" },
  { code: "PHP", label: "PHP — Philippine Peso" },
  { code: "NGN", label: "NGN — Nigerian Naira" },
  { code: "ZAR", label: "ZAR — South African Rand" },
  { code: "AED", label: "AED — UAE Dirham" },
  { code: "SAR", label: "SAR — Saudi Riyal" },
  { code: "BRL", label: "BRL — Brazilian Real" },
  { code: "MXN", label: "MXN — Mexican Peso" },
  { code: "SGD", label: "SGD — Singapore Dollar" },
  { code: "MYR", label: "MYR — Malaysian Ringgit" },
  { code: "IDR", label: "IDR — Indonesian Rupiah" },
  { code: "JPY", label: "JPY — Japanese Yen" },
  { code: "KRW", label: "KRW — South Korean Won" },
  { code: "TRY", label: "TRY — Turkish Lira" },
  { code: "SEK", label: "SEK — Swedish Krona" },
  { code: "NOK", label: "NOK — Norwegian Krone" },
  { code: "PLN", label: "PLN — Polish Złoty" },
  { code: "NZD", label: "NZD — New Zealand Dollar" },
];
